language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: VVkGtstEZlxvG8gx0KThQDM8e+DKaXpobjVuJ5boVxvj7H0tIfaRgbxrU8CUEqbipDrYmKWXDYegeeJGUeaOLT4+5BhjdJeeZpETkTOELaUu1AFSJ+y6rufxINTf/GK1luwUQxfOulft4OiVrba0MGNteZ26/wT3l9tuYUcVvAXOGnvL3DZD4JFUDI08VsHaYEhIhTkS6ej4HFUKVwmcq2/wf9kZ96gPhC0cMQGD2R2qPwRCbCBFISTzxWHbAiLiaBwVdN7FtmESX7eVwbFMQUqjOaKhUjp5yjLKZYGgghXzHYoQZ0DtXln+IOE1r6SywjaFFWNMvgE2k6RoODBofY2YVb35EQkuRcUYQRZVYcb9mn52lrY1BAKzeyCw8aGhkmp1ur88bSHYRHA+6oA14q+vp6+5Ple8VQmO7lGW/lKf1bvuoaFYF/pCoZR74LgfimjYFkqxawLEdc55IcVtLrus1mBo0DkeGqkGxsHp87YdcpzYAgH6BK4un6KXvlPWjIufxr6JwLwjWqLcNd4tHxk0vZR7Kd9f2JcepCh2A3t4xbqw87j2aKP8h+plxTPj/nhiZRw7PGGfOP4iqATXjLBh7dkG3ZFxg9hfgD8gZyLvcMOi0iQ0BGITqhyBllubtP44Has4FjCLwzis1CJb+W2WqZeb9JkQYKlQDteEOXQ=
  - secure: Id5U9QzUkKJYF6pWgNxfEzxmK8hdP+9/SSHHXe+EE4BqZLg6eNuPJUOzn9qYAE7jneocQgIJAiaq8eaTMyhIdI6HnyF/Ob4Wuyy6ZDjrUxm5TsFgmaMyz7sG1IKKp7/JPL22sFLNO9uOWbnm/5vO2tEPl5OIi5IOyIy3phkzBXSFf31G6ynEAWGivC3fx8Qt7aQlZnqfLK4UDCGoRsPd4puRTB8vm1gCclGmnuQ3o3nChBf+zJO3uKcVBwfxTa0i9ha2kta01J4lw2A7DDglHEM+8PKHJq9qZUmVIxc9UR41s6T7qLQMTc4bJhGxlHGTC/O/BZLmw/jntPRe9zDDwhbwZ5H3frV4QW+DRl/wyh3lSKjed1zTsnwNH9Jn4v+N9FrpJrr4kCNA/fTpeIZIljPqoL6Q17mDsxtwxkANlvFtr72hGUneDSpQQTN8ooj6zNpa74Zp4IbUmz+09f8u934ZXt1w/aV2GNE6UXBpYA7/yMwbA9hao10zBJDOWarzIqhO4Lr7Qyu1XVaXMvpYJ0+b48TR96EHpzQYVTvWAMEeLFf88SV8995q7WshhoR5fJU6aIxPK2eop8rNGGNeqTKHCagf1nzlAqXG93FPKwMlSNd51Bse69d8uqTFNNbCf+atJRbO6+LMAnkQwxuT9xrtBnOjoshnMA97e8C3z74=
