language: node_js
cache:
directories:
- node_modules
notifications:
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: ZShuzfmjOkYvmoS/+lypn9tTGOEntMnopS8/zLQ/yLU3ZyA6ArsWXXt09Fo3J8fFRyzrRdHG5sAe7wQ7plnLyUBS+fd7CXyvkQobBW9yb6xvF333DnA5U1rCiF3x3U3DNNcID/Lgs3CkyfDp+TiH5l+Bd3RShirTNKNmNnR4BV9U/uAGFn/Cl6/BuyUy/ynJmpBX3MPD9gBD32pMHeBxJN857TFiHHLPpfNPJSvZ9Ft3Q/0bYWjsElKRusJBZFGjCCIaPMBKFg1aU2gCjPnDMuMl29fYk1vcnKljjUR+yiEF0i2iG/6qW7T0Aascmzy5fmz+4ZZspYcJpfTaHWh497CnOoUujkH07tD83HGGvdhsSxDUSehqD/WrH2tZVz3PvTKjIgApn91tslXUIvIuyxzQDbEXiOh0kyhyBVG7WEbUnWGOCScIxC1o/4HB17KJqp+7FLH2q9iq1p+cGennincDupAovknteWrAC6eNGtuwF53cjsrupsy4PsXzgwKtSbqIUsqi6ruoC9pY/CE28tVkjKALeu+4ed7KDMAviLgAJaQ9XMTHD5zwzVpegQ8NRELUVvbf92+NSmbtNtCyTGW7vN7ZbQGhrKR3AC1q9KEMi217CYUjfnR4XgQ8layl9K/Q/BRQg/HVsvXO/5wR0qv2mtMCvgzAD6bWminZs0A=
  - secure: B88QjTzrkPpIsEbLVQOCnf7lJuo5GyDX64DprxUWiXGTSBUUqdHMoqYhZy6agaxFcEFhk6MRDIvJz8T5hno/N1QBUa1lqb1zUmeholTrJL024u0Tfq/HF8qoPNmx8i2roIxMXwCHX9foSmur159GQs79IF0Pnb9r51vYseq7xeZr4xOrdFaORnvZ5R3vHm8npwwCU4wxbwXReAJYqf3AYMGFHeqkRu95Ql5/53SeXlm7p5VlKife4XWMHOerPnxoLQU9DnmMbix7wj9BYm8tDf5vzvKhOu9z/1fmUngmarinhXAVU21zhFyKh9N8eSbUKvWPKMhY7G7vt+cw5Ott0WPUU8citkfkPJc8+kg1c5nA5OdODs55Ct01e4HyjghRKkI+PUgqWMyNuZQs0l0Vg5R01K0+fwIpmNsuK0dj977vKkPZ0GQ4UTtI2oFtXbyAPfrZ9l3m2s7clASONWey7PmDykXIH/Ik4n4MWymz6cu11+ZHk056B4RDSyTIs6HyjHoPDUhzWljPsE83j195R7oD5eCtm3Y1H6VrSUhxc9JREWPiOz2OU/JKwOWoL8fscojAAnfDqEZdKg1pBwFJCPe66XP/R+xthyMW48cmCDppBaSt8F7MsInLD+qMh0pcfgQMmeAg94N6mM4JvlVm/s9Ci5TUV3+k9zpPJ5ZeVQA=
