language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: tS+AyfD/kjFmGxPHRCSyJ9HAAxqHaPBVkXgSzkyXp1T1T8/XqDiRdtES/I6MqrPQgqvuZunlzX2f9tqkc07I0PV87LkSbKR2n+hwU2RqqsqAnTfuDxkeY7H09QwK3ImBv6mzpchT+LV5r0CBiboOpj5tBuHPjQ+zUYIsA2B8+hzCCscOMp4UYR/wKpfIO81BCb0WVhS2KPUGo53KkfU0ZTd+ilWFw7lRBJXCuCUJjbtrAkdTVgBX16w/nj47h8PrgqrN8X3gnSEbXKpndsMFz6eXNAOQ2ZlUnrowxlmVQWFFAeDwQst30ISnAY2zt51y0njECMBu17y0LbW09im4yPyTA7DnT1z5O/xRv7jR77J0dJciVhSCgR4Wa2/P6Tr+e23MGiXljWDr4aSmHE8KgpsEsHgYJeCpuw7Ah3pdGe/TpjLtcL5HgkJZE0jFRdTYmAR1qspoJcnkKAIc9jvG0rDpnyN3isoFA1KmdmQHS6tb0p/KcBi9K1s1kC6OZQt+QaVkouB5zOFLD6G4UnoLlmyl5ac0sJ5tnAwbkMul3bkRiUhTofbf3yhSYu7oMb0ivMf4mn9xGoKX3BEiMoMOi8rMfHV+xeBNywaMoS4xTsprjjrFnHTRQoMalPv5HHxchjDdqEIfWl0YDSFHshcsk4AAr8tl1NprOZ9W7lZU+qI=
  - secure: krxp/gzilvvFXL3x7JRCv+3sautheK9lTbXGmop+z8Tf8aNFd6pcGnBVsLX3ly55gBuUdtDaiatrskGCDHCANkD9mijpLNBztoBxsqGZCylXx+ze9vEqfYc14czZnRy5Sgu/qML5yi4HW51HDJbf66EWkDIkaAzloIboKVCKNuJzlXXFmPPfvgL5kybiEObQCqtX4ziqfKYSwX9GM4JKq1wYHTpMv1h/C2bcEBcKgX+/A/dVxqE+zGrFyaS/RyoTbkMSwG7sT4oO9zbf2OhqIoJNix3h/VER9PZyOgPe9Py0RBtx29qkF7vMyOA5Et8yy2CqGEhnBqrhLjBMf2lQRY8Po8ZXB8Uo2+PxTnR0bOvCHrKWm2KyxoIk3JEOFiCJ41BG9slMvsJyyui/J75DeMVPygQ5NlxwnCUEkW9ZH3LTnJSAZ4qOI/XbL6S1ZERIf3Ql30H1SvExSgi/xvW15eUvE8l6Rq3YjvdvdXh8p0dyPHDsWCNKmDw4b+cqFWmnFN0rBzEB+pQnTcZ7KBx7igcCxVlqpp51CqDqNbuec6p1N8JzlvC98quuTLqI3yn/mAJKImnfuMh0njulH6VRaVViszcxeEOY0hsue/KfJRIWk7BHJ4IHKis1fcDgUiFouyi6XlF5zOFx+uVWdlpo7iWxLEdoYTYFl1+22uYBZPo=
