language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: Hew3LUvAv4HiaKXzH/2sS0tGBlqLZxy1EuiKnk+wzGOi6ot6zsk+tQihVF7PLIv3Z0P8AfBPV9GbITbyFABvNUqBKdyGrVD1E6DqYGYewgQFnyGwEBPzGvwi/7aLloAhozklF3tuxLHa8eV22nyfj1ZVvZyTomCKS98SKSF1McS/nq9O9ydM1pfZJKJxfvzbb6puPcDnd26Z1QVAq3/bGXtxP6H3FhDqGZyJWLsl1jZv/y7ccLB4fzYniuQR9OprNOvhK12FHg/sjX/SELyov50Nc6nJbLdpEyrT+nDQW1u4iYI8UKUhD+tAyqRYydVYBZRZiQhAkEPSARtnEYw7/kUqL96pbItE5Y2HpBDlMJIdSk3RrUdG2XBQW+Os2R6nlTpJiX4ZPEtuU/nVwaNfvzARbq2NgoFoWXhwCpVMZ6IP+UazJnGwCap6WhvLeuVoXxll6jxEZVrQe2bdBcEM5Ru3osVbMNZmZFzQ9MbljFROi35CjfvcgwbZ3elYT4Pyalu2/MW1slxepaXyIo8ZG+zG9Ebpvzh2B0Rd1GWuXiLDVRAkGRZmuhwwrCF4zgAutjPHyHiTMaRpHJRc7JslAvNeoRE9sfTj78WSqhgbzvmyyb2fG87Azfwuofkz5exDUVsM0az/lLq64RTzDYruOE5PXjjaf2M6mTjcW1VelDA=
  - secure: gkn1gLDN8vxfSib7LAUZPf4ZFUUsmvpfQ9Pj0lMO8dHhtqhjTXk+uZYML3me53GeDYOyXHMRbEs4E5TMVEsp6Zkmq2MvgBqJMv4+eTTi2Q0IDp50oQAMducRA0HAkMyLZjSRtxCulHnL1uVADda9T4IZ7zqoc7hG9Oknj5Vm4ruoJ1fOtSS97vq1RJQqqo3UxH6J38Rqks8QHXmnbWFciiEBbOQSWqkM5OHaaKKYLkEpV3M+ifKNqrzMFJok/l0rT0hINGOLCj/11IrnxkgVV3AXB3s6BmRdbRNrgsB3AXYhgQg0a5u+19Lw+sVc/MmvlfzHzyN+3Y4UdFZY3fGajzjIfQ67ZYAK8CiT5IsLACXTwvkxp8q2nR11FYskZz8G9Pui40Zgj+NhKF0bfYXAVInHygYXvtbyBJZlI7rzNJfVr2OTii4blejZEtBDxZ4i6Ntqf0CrxQk3xOYgl88sZHt2jWBgJuMm0gYED8XYWVdR/xQB6UBgbKKs3r+jSeehtf2GL1TZewWFJzgw2DuAn1coQYYDRNB2lniX3bkRnocFL4RIRXzZn9RRIQH2hvftlSgdY3gA2P63vdXdMsw8BZiFt3XYlvXFcfKlkL3/Yy4YQRmQbKckPBExRcmK1JlOMdJkY3dIBsEQZc/DtaTS+EdTOkzNZH2z46YPP4ocFOw=
