language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: bmJ5V0SST66c/gvmxb+azZ+A6ZXklsBKzxe7gVKBV7cdF5yZpyYZODrHNjBfiMWCKx3z5DHnfpylfYowK3GnBnJkaT19z/H+C6L5btfkyeJkvTlElIaoSv41wVPCLnjOXfUMtG5KQBfH81DQtVtwUrJN24m4tKa/TllvqZmlZmdkyOEJEK0oxdUpsHFgzhIjs+2xoE3yXWA91VCjviTi7Dy6cgEu5qeuvEihVMfxN/AK5d91+V+m0E/6GQm3yHenMwFA/WzTEYMz9/RRX4HMWt142YzoR5fj282BCDyg21NEmtx1ffnaEHaQN0Mu3hPPOPxaWLSBi1BaYgbFT/GzbzOvXiUP7JZkXRD1kpsnc1IWgVI+7/t70t/sE4jfgG47eW3rELTBguOcmI+MvHhHej4ynjVY9wjjb+MMNB9U92sEbUcNkIGkjDA5GawxNjkOl1GUHiSWDxdf7897Jmd8yaP6xmho6bTZU/Gs9LC8I4IPIXbe/7Wc9Hdxvs12aZPdyZtO91GRbquh9QuvLBz37DheLAgMMwZRL1En6tTaY4maNO7kXf4lX3yUqUWRKcP+RaY/QKryLrnw/F0CZFpjPDDK9eCp8zW5Ld4O2b+O276VcPbeH+HZgMGx5A5tADvKQwDCy19zB7cerz9l34f1i0bdHqp8bpNHgOZXJAVcdys=
  - secure: pfu2PompfhctCxTik5T8e604zJ4Mut7kRunPHsYTwy18osv36YwTVn0ZQHES809EdjCRAFEuFM4Y1rCPLdrrFx9uzwWALfQbK6hKA4B835b/D/KOAY/tR2YLMhQunHS79eKBDZTXoQU29lTAslAYctGtMC1DPqOQN/TFtBdr05JbdY1iaCh6JKOB1+ZRxfN3YYbo61Q0NMxsTYlME/S6UMOXSxv2ZE3kL20LC4Rvs9EWAKOTpRZd/t7kDfRnMOzB5sAFSaGTDj1BGB0PKXlyn1o4INscVH+fMem4awz+3IdU6EFVOzbiosicHhp4yzOWcbVt2LWPt97WtWGu8W+T1XO9Gn4w7Bv4/18xwmbKWurP07+79Zam7I3o2K+FtqKORhEFIIOKaqv0kEIP7VtG56KRg3yrNGHYIna8Kc9l1ILq7cgjxLmzVyWWazvIuqNRZWQfPAANwA6r7zWYR7fUYQflvpNuAaonySlSi0tAfZ1L12ptSM0ZoE+zz0cpC8wtE8Di34z80xIKS8G0vCMMroT35BfLt6eEVIQcstBnZnAKI3stgPdZngg9icMAwqYVJ+O+8xyqwcoEwV8NrfPoLQoCStSl8DWxgtEcN8krOWzQJVHQFnWsYlJfk8laPSOpPbVx5/jDM5FyMKDj1sdBaLXMIhfNsM+ONsJYFr/gJWc=
