language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: bmJ5V0SST66c/gvmxb+azZ+A6ZXklsBKzxe7gVKBV7cdF5yZpyYZODrHNjBfiMWCKx3z5DHnfpylfYowK3GnBnJkaT19z/H+C6L5btfkyeJkvTlElIaoSv41wVPCLnjOXfUMtG5KQBfH81DQtVtwUrJN24m4tKa/TllvqZmlZmdkyOEJEK0oxdUpsHFgzhIjs+2xoE3yXWA91VCjviTi7Dy6cgEu5qeuvEihVMfxN/AK5d91+V+m0E/6GQm3yHenMwFA/WzTEYMz9/RRX4HMWt142YzoR5fj282BCDyg21NEmtx1ffnaEHaQN0Mu3hPPOPxaWLSBi1BaYgbFT/GzbzOvXiUP7JZkXRD1kpsnc1IWgVI+7/t70t/sE4jfgG47eW3rELTBguOcmI+MvHhHej4ynjVY9wjjb+MMNB9U92sEbUcNkIGkjDA5GawxNjkOl1GUHiSWDxdf7897Jmd8yaP6xmho6bTZU/Gs9LC8I4IPIXbe/7Wc9Hdxvs12aZPdyZtO91GRbquh9QuvLBz37DheLAgMMwZRL1En6tTaY4maNO7kXf4lX3yUqUWRKcP+RaY/QKryLrnw/F0CZFpjPDDK9eCp8zW5Ld4O2b+O276VcPbeH+HZgMGx5A5tADvKQwDCy19zB7cerz9l34f1i0bdHqp8bpNHgOZXJAVcdys=
  - secure: WlXjQxG1131hYRkw03sT6UO/5T9QJ6q59F5YDf3aff4W94HriSrEOltrqdebhv5QV1y7BaFVrR4VBxRkTfqP7mjmBAmGZRJvYj3oFd6E3wsS/7ILvTBh0X5DB9UsANQJ9Hc0swdlxsAuhhwGHPwlFw0mN5fvNvgfaXwPi/W+MokDRwXJzAvJoS28oEScUsKVLbASZyVZn8I8Iap7oIJHSQwLpUn5n5BERYfRrzTbfFpzm3QZY7AE/bt99VkMunSAxQiR88lzMhNUKzITkoqxnYfwmUGc9vlJkJ/SI/VlVMqYet231JRKtJBMPazYxVK72cW/L6u9Zd6Q/4f/MT4TwuymtDtLwuDjYd3XGoMST8728+skVxGsESy/z1KcbjSrKMtn0LCJobtrwJyzs4bCcml9RCeH22d/3LpPkZ9LZlc4U2R3+J46KYnv7Awgsd9U+p/ha4mFDQQ5WobGULsM0p8Qj9fg9GkAxC0Oy2ugVmhTuEoT+EwmqZEAUMzlT1UtQ/2SQMNCdM8UvKf4I+th0eYwv2koDJmMtRzqfS1Kpledguvh5FR/EFnE5vm8YwNa4uLSMIi7XSnsybW1qz5aSWg9Klv7ckL6uSjeDpo9+QvJVpm/hpb7GCzdIC98Dx/UwZ6x2y9YbrgYZyYcwE6zT66n9NyPBN1GPheTlL5tOOA=
