language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: bmJ5V0SST66c/gvmxb+azZ+A6ZXklsBKzxe7gVKBV7cdF5yZpyYZODrHNjBfiMWCKx3z5DHnfpylfYowK3GnBnJkaT19z/H+C6L5btfkyeJkvTlElIaoSv41wVPCLnjOXfUMtG5KQBfH81DQtVtwUrJN24m4tKa/TllvqZmlZmdkyOEJEK0oxdUpsHFgzhIjs+2xoE3yXWA91VCjviTi7Dy6cgEu5qeuvEihVMfxN/AK5d91+V+m0E/6GQm3yHenMwFA/WzTEYMz9/RRX4HMWt142YzoR5fj282BCDyg21NEmtx1ffnaEHaQN0Mu3hPPOPxaWLSBi1BaYgbFT/GzbzOvXiUP7JZkXRD1kpsnc1IWgVI+7/t70t/sE4jfgG47eW3rELTBguOcmI+MvHhHej4ynjVY9wjjb+MMNB9U92sEbUcNkIGkjDA5GawxNjkOl1GUHiSWDxdf7897Jmd8yaP6xmho6bTZU/Gs9LC8I4IPIXbe/7Wc9Hdxvs12aZPdyZtO91GRbquh9QuvLBz37DheLAgMMwZRL1En6tTaY4maNO7kXf4lX3yUqUWRKcP+RaY/QKryLrnw/F0CZFpjPDDK9eCp8zW5Ld4O2b+O276VcPbeH+HZgMGx5A5tADvKQwDCy19zB7cerz9l34f1i0bdHqp8bpNHgOZXJAVcdys=
  - secure: MzvccbNAOEruI3IVznkpNIQ87hDukhakVnB0htUia1QHupAzlY6UXrC+XakWHayfA5spd3QczJusbB3ZT35KCBC0/UqEwFgwLdJjXVNPI/WNbtJGdB7qASSYoVMGFOLUP7+V9gO9BtYe0SiM1j5VptUyqcuxAUHjThl9gLeUf1dK1iCwxc9jOMlwIF2niBYHwcSPza/kNHdoY2p+Dwncjvqt/gdDfjIId6Ubazfg1sNisqheIrC1AgHorEai6TWI3sF5UEJ5fWDRYUo+PHvkk/pICU9bjojB+NVz4CmhSytILNuzFvzs0Y1iMUl5J/pG2MNmi8a9SSlHQsusNLfqpx2xJ7kPS2bGZk4f6BPUshQ7Xu1rnzixAox9D0e5XnuBWcmWcf9jyzB09v/GmBlWtWia9HFBG6Ln1rrPsG/AN1W4SaevDW6LJTEH2D8uCm3aby7FXxp+eiB5URx7sEQOqMJYcdObqNIYNqu7a3Y0itRGbc6VvGbxncQbefbJwgaolqVPwrP/eNOftvNKQg+Us96I6jzSpbWj5spX+NbXuMkfT3VsTRo6Qq1CifeBpXem89E7XCFG9LnOJoFrD6qeWRbNHcDMHMLlXTuzQAuq8k+aXjHfzvThsgbhOJebTvq9JC8NlwAI5BmLuW9bXdpuD17irzfJK9Gs/dswfZE24Lw=
