language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: i6tyCZFm9k2+U2r6S9zXv7yYmMwECAGdhNBkKSsoWwyQrAaWKmV1anQgj0OW3SH1ix7f7g2EKY1Ec+ctZSB1XO0Eex00h6Z87h9e/JOYYaZF2ZB3prCVV76HvJr4H3abNg/Z5CK0ejW5/UAVewOfrGjKWW2qul4ddL3FzZYpWGH9xetjv24LgVFrZIlBZrjKjXH8YKrSElg3NJuG7g7G8QVQMKEx4RAEA/k6kBnPZ+btlh7f/wrMAOaW8l7diT5xQPvzx/w2ctH8w2VQTFbNja5YX47VUUVDT1XHG18xrgReJCk5JvahKZGM9a14lA8bn45GVvU6tYpFJFeniBOhLNJMwNv2dWQ3fjszZwE8OtpqvhBvtjculB3A059RGSQq2Y25aTEMDC0D32e+m56i/9FzmK9PrbnKI3V5Kod9QHSNfy85msln+nGDmyQheQzt4usqN+CBT+9zTcjI2GEyZPk8a49JFASwow61tZ4m5YkJIQKDxjsQS9wsSj5yFBnGPO0YyeUcftuCX/SXI6fdv7XttfS7zgfBhvzcBurgb8a/f/AYWW7q2sgoi9XzcXhXEUBphOUut4avhpyoIlTsZoi2onJ0yiLSWXBw6uBGlz9PYvugIUuO2NNrDLJh7ITq+U5TGl5poDEx1Q1ACr2FVLMRpGdiyO+Guq9hlnnpieo=
  - secure: SF3PeFInbAtOdv7wrGzXMDwlYXqqQ0MiqzkuKVLNerInr16BXA9wUYy8fKc21HXv/cS58cfZ9GWUl8fbA10CBJICYw+ggka2aFz5HfcMLbYEo1AD+wfgb1Lc8EIJ3BO82SG6f91C4LsaRmBMsguDV2Z7jnoRldvvi8xXh2y7lg3dSiEDK/b89ERYQ2rDrTS7iYR0ETh5W2lWFRU8fOV0Lm45VtLjNEP7+KaQ7FOvViyi71usBrplqsJk6C4kg0VTCLSAZ+tOjDf/LO4dntjrAofY5IgqcPrKLBxmpZ6IWuI7JYTT5Y93R8T1TuEvXl0NBf3IQ6LfZtYiYYxm1xm8Nb3tQW7PxfcvbxGh3KJA9fcE85jmrFeRrb0gTiIDZxAFzJq/j2kYyJkwKNZpr+gs99PfNND8GJIESDnZEEmkgHhO4XbuoK1mGB14iyEPiBF1xEaoKUDHoebDR/PXWIpznCHrfM16TGW7MUOHJJHyHCfI6fUKoLqThvwJLepp2Id6AFiaw1Gb3vKrdM1NrUYyBokIppS/Y1nR9qtlLP4ufIhkOw6HiMZyk/mHgcC4SWyJbKZwjjU7xYV6UBR8DMF8C8AkIWQ7rhBee6l53wWbNIHXusgYSngp+dR4kxlJ87WkXY4sF/J1d+O5bqCLrX3eG3BF3bx2NxUfkIx2AxcYJTg=
